MODE_NOOLITE = 'noolite'
MODE_NOOLITE_F = 'noolite-f'

MODES_NOOLITE = [MODE_NOOLITE, MODE_NOOLITE_F]

BATTERY_LEVEL_NORMAL = 100
BATTERY_LEVEL_LOW = 20
BATTERY_LEVEL_DISCHARGED = 0

DOMAIN = 'noolite'

CONF_CHANNEL = "channel"
CONF_MAX_CHANNEL_TO_SCAN = "max_ch_for_scan"
CONF_MODULE_ID = "module_id"
CONF_BROADCAST = "broadcast"

DEFAULT_PORT = '/dev/ttyUSB0'
